# -*- coding:utf-8 -*-
import os, configparser, traceback

try:
    print('>>正在重寫ini...')
    config_settings = configparser.RawConfigParser()
    config_settings.add_section("收集nfo")
    config_settings.set("收集nfo", "是否跳過已存在nfo的文件夾？", "否")
    config_settings.set("收集nfo", "是否收集nfo？", "是")
    config_settings.set("收集nfo", "是否收集javlibrary上的影評？", "是")
    config_settings.set("收集nfo", "nfo中title的格式", "車牌+空格+標題")
    config_settings.add_section("重命名影片")
    config_settings.set("重命名影片", "是否重命名影片？", "是")
    config_settings.set("重命名影片", "重命名影片的格式", "車牌+空格+標題")
    config_settings.add_section("修改文件夾")
    config_settings.set("修改文件夾", "是否重命名或創建獨立文件夾？", "是")
    config_settings.set("修改文件夾", "新文件夾的格式", "【+全部女優+】+車牌")
    config_settings.add_section("字幕文件")
    config_settings.set("字幕文件", "是否重命名已有的字幕文件", "是")
    config_settings.set("字幕文件", "是否使用字幕庫", "否")
    config_settings.add_section("歸類影片")
    config_settings.set("歸類影片", "是否歸類影片？", "否")
    config_settings.set("歸類影片", "針對文件還是文件夾？", "文件夾")
    config_settings.set("歸類影片", "歸類的根目錄", "所選文件夾")
    config_settings.set("歸類影片", "歸類的標準", "影片類型/系列/首個女優")
    config_settings.add_section("下載封面")
    config_settings.set("下載封面", "是否下載封面海報？", "是")
    config_settings.set("下載封面", "DVD封面的格式", "視頻+-fanart.jpg")
    config_settings.set("下載封面", "海報的格式", "視頻+-poster.jpg")
    config_settings.add_section("kodi專用")
    config_settings.set("kodi專用", "是否收集女優頭像", "否")
    config_settings.add_section("emby專用")
    config_settings.set("emby專用", "網址", "http://localhost:8096/")
    config_settings.set("emby專用", "API ID", "2060b39380c84f1896286cfbbb9f2d17")
    config_settings.add_section("代理")
    config_settings.set("代理", "是否使用代理？", "否")
    config_settings.set("代理", "代理IP及端口", "127.0.0.1:1080")
    config_settings.add_section("百度翻譯API")
    config_settings.set("百度翻譯API", "是否需要日語簡介？", "是")
    config_settings.set("百度翻譯API", "是否翻譯為中文？", "否")
    config_settings.set("百度翻譯API", "APP ID", "")
    config_settings.set("百度翻譯API", "密鑰", "")
    config_settings.add_section("百度人體分析")
    config_settings.set("百度人體分析", "是否需要準確定位人臉的poster？", "否")
    config_settings.set("百度人體分析", "AppID", "")
    config_settings.set("百度人體分析", "API Key", "")
    config_settings.set("百度人體分析", "Secret Key", "")
    config_settings.add_section("其他設置")
    config_settings.set("其他設置", "簡繁中文？", "繁")
    config_settings.set("其他設置", "javlibrary網址", "http://www.p42u.com/")
    config_settings.set("其他設置", "javbus網址", "https://www.cdnbus.cloud/")
    config_settings.set("其他設置", "素人車牌(若有新車牌請自行添加)", "LUXU、MIUM、GANA、NTK、ARA、DCV、MAAN、HOI、NAMA、SWEET、SIRO、SCUTE、CUTE、SQB、JKZ、URF、SIMM")
    config_settings.set("其他設置", "掃描文件類型", "mp4、mkv、avi、wmv、iso、rmvb、MP4")
    config_settings.set("其他設置", "重命名中的標題長度（50~150）", "50")
    config_settings.add_section("原影片文件的性質")
    config_settings.set("原影片文件的性質", "是否中字即文件名包含", "-c、-C、_C、中字")
    config_settings.set("原影片文件的性質", "是否中字的表現形式", "㊥")
    config_settings.set("原影片文件的性質", "是否xx即文件名包含", "流出")
    config_settings.set("原影片文件的性質", "是否xx的表現形式", "無碼流出")
    config_settings.set("原影片文件的性質", "有碼", "有碼")
    config_settings.set("原影片文件的性質", "無碼", "無碼")
    config_settings.set("原影片文件的性質", "素人", "素人")
    config_settings.set("原影片文件的性質", "FC2", "FC2")
    config_settings.write(open('ini的設置會影響所有exe的操作結果.ini', "w", encoding='utf-8-sig'))
    print('寫入ini文件成功！')
    os.system('pause')
except:
    print(traceback.format_exc())
    print('\n創建ini失敗，解決上述問題後，重新打開exe創建ini！')
    os.system('pause')
